version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  run-tests:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: |
            python -m venv .venv
            . .venv/bin/activate
            /home/circleci/project/.venv/bin/python -m pip install --upgrade pip
            pip install -r lynk_up_server/dependencies.txt
      - run:
          name: "Run tests"
          command: |
            . .venv/bin/activate
            cd lynk_up_server
            pytest

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - run-tests
