# Generated by Django 4.2.1 on 2023-05-18 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lynk_up_server', '0003_friendlist_group_user_delete_friend_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FriendList',
            new_name='FriendsList',
        ),
        migrations.AlterField(
            model_name='friendslist',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends', to='lynk_up_server.user'),
        ),
        migrations.AlterField(
            model_name='friendslist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='lynk_up_server.user'),
        ),
    ]
