# Generated by Django 4.2.1 on 2023-05-18 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lynk_up_server', '0004_rename_friendlist_friendslist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendslist',
            name='friends',
        ),
        migrations.AddField(
            model_name='friendslist',
            name='friends',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='lynk_up_server.user'),
            preserve_default=False,
        ),
    ]
