# Generated by Django 4.2.1 on 2023-05-19 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lynk_up_server', '0004_event_description'),
        ('lynk_up_server', '0005_remove_friendslist_friends_friendslist_friends'),
    ]

    operations = [
    ]
